on:
  push:
    branches:
      - main

name: Package

jobs:
  package:
    name: Package distribution file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Install packages
        run: npm ci
      - name: Package
        run: npm run package
      - name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git add dist/
          git commit -m "Update dist" || echo "No changes to commit"
          git push origin main
